### PR TITLE
Link to NSSpain talk

### PR DESCRIPTION
**Pull request by vitalybaev**

### CODE REVIEW

**Comment by nguyenhuy** [comment]
I think this edited version is preferred: https://www.youtube.com/watch?v=RY_X7l1g79Q

**Comment by vitalybaev** [comment]
@nguyenhuy fixed it

**Comment by nguyenhuy** [comment]
Great, thanks a lot. Need to wait for @appleguy to merge though-- I don't (and shouldn't) have the permission to merge PRs :P

**Comment by vitalybaev** [comment]
@nguyenhuy Sure! Have a nice day (or mb... night?) :+1:

**Comment by nguyenhuy** [comment]
Thanks, you too. It's 1pm over here (EET).

**Comment by appleguy** [comment]
Cool beans, thanks!

**Pull request merged**
