### PR TITLE
Change placeholder boolean to time interval

### LINKED ISSUE #282: Change placeholder API to placeholderFadeInterval
For finer control of the duration of the placeholder animation. Default to 0.0 for no fade animation.

### PR DESCRIPTION
**Pull request by rnystrom**
fixes #282

### CODE REVIEW

**Comment by secretiverhyme** [comment]
What about having *both* `placeholderFadeEnabled` and `placeholderFadeDuration`?  I'm concerned about requiring folks to set a duration in order to use placeholders, since they may end up doing something ad-hoc (0.1f here, 0.3f there) just to get them working.

Looks like we're now disabling placeholders by default.  Intentional?

**Comment by rnystrom** [comment]
We previously disabled placeholder animations by default. Just keeping it consistent.

Regarding the duration/enabled bit, what if we keep `placeholderFadeEnabled` but just override the setter/getter to adjust the duration value? That way we are mucking w/ a duration & bool when deciding when to animate.

Thoughts?

**Comment by secretiverhyme** [comment]
> We previously disabled placeholder animations by default. Just keeping it consistent.

Oh right, sorry — I misread this as affecting whether *placeholders* were enabled, not their animations.  Carry on, then!

I think keeping to one property is the way to go.  Let's stick with the NSTimeInterval.  We could even make it a class property instead of an instance one, favouring consistency over configurability; normally I wouldn't suggest such a thing, but given how limited the built-in placeholder animations are, perhaps that's not such a bad tradeoff.

**Comment by secretiverhyme** [comment]
Let's ditch the `placeholderFadeEnabled` property entirely and then merge this in =]

**Comment by rnystrom** [comment]
The only reason I'm keeping `placeholderFadeEnabled` currently is to deprecate. I'd say we push this in 1.3 and kill it in 1.4.

**Comment by secretiverhyme** [comment]
Push this in 1.2 and kill it in 1.3, you mean?  Sounds good.  =]

**Pull request merged**
