### PR TITLE
[ASVideoNode] Various bug fixes

### PR DESCRIPTION
**Pull request by ejensen**
~~1. Corrects map between `AVLayerVideoGravityResize` and its corresponding `UIViewContentMode` (`ScaleToFill` instead of `Redraw`).~~ https://github.com/facebook/AsyncDisplayKit/pull/1549
~~2. Changing gravity now updates the placeholder node's `contentMode`.~~ https://github.com/facebook/AsyncDisplayKit/pull/1549
3. Switching assets now updates the placeholder image.
4. Placeholder image is now cleared in `clearFetchedData` ([prevents runaway memory usage](https://s3.amazonaws.com/f.cl.ly/items/3i1b3o2G3o1D1u2Y091c/before_after.png)).
~~5. Replacing the `playButton` now cleans-up the previous button's state.~~ https://github.com/facebook/AsyncDisplayKit/pull/1549
6. `_player` layer is now created in 1 place instead of 4.
7. Simplified visibility state change handling.
~~8. Fix video stalling caused by backgrounding & foregrounding the app.~~ https://github.com/facebook/AsyncDisplayKit/pull/1549

I'd appreciate an second set of eyes particularly on 6-7. I found it difficult to follow all the cases in the previous code. So I very well might have missed some corner cases. cc. @lappp9

I'd also appreciate any feedback on the best approach to make placeholder image generation more flexible. I'd like to make a way (in a future PR) for ASDK consumers to provide placeholder images if `AVAssetImageGenerator` is not the best option for their use case.

### CODE REVIEW

**Comment by appleguy** [comment]
cc @ekurutepe

**Comment by lappp9** [comment]
Hey @ejensen, I'll take a look at this tonight and let you know if I see any corner cases or regressions!

**Comment by ejensen** [comment]
I've implemented the placeholder image delegate method mentioned above. It's based on the changes in this branch. So I'll wait until this PR is completed before creating a PR for it: 
https://github.com/ejensen/AsyncDisplayKit/compare/video-fixes...ejensen:video-placeholder-delegate

**Comment by lappp9** [comment]
Hey @ejensen this looks good to me! The refactors definitely make what's going on more clear.

**Comment by ejensen** [comment]
Rebasing and splitting this PR into 2. First up is https://github.com/facebook/AsyncDisplayKit/pull/1549

**Pull request closed without merging**
