### PR TITLE
set the right attributes for block properties.

### PR DESCRIPTION
**Pull request by Yue-Wang-Google**
See https://github.com/facebook/AsyncDisplayKit/issues/2111

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
Can one of the admins verify this patch?

**Comment by Adlai-Holler** [comment]
I believe these should be `(strong)`, according to http://adcdownload.apple.com/wwdc_2012/wwdc_2012_session_pdfs/session_712__asynchronous_design_patterns_with_blocks_gcd_and_xpc.pdf page 83. 

Additionally http://clang.llvm.org/docs/AutomaticReferenceCounting.html#blocks states that:

> With the exception of retains done as part of initializing a `__strong` parameter variable or reading a `__weak` variable, whenever these semantics call for retaining a value of block-pointer type, it has the effect of a `Block_copy`. The optimizer may remove such copies when it sees that the result is used only as an argument to a call.

So for stored strong properties, ARC will automatically copy the block.

**Comment by Yue-Wang-Google** [comment]
@Adlai-Holler  done. Thanks

**Comment by Yue-Wang-Google** [comment]
wait...

Per Apple:

Note: You should specify copy as the property attribute, because a block needs to be copied to keep track of its captured state outside of the original scope. This isn’t something you need to worry about when using Automatic Reference Counting, as it will happen automatically, but it’s best practice for the property attribute to show the resultant behavior. For more information, see Blocks Programming Topics.


https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html#//apple_ref/doc/uid/TP40011210-CH8-SW12

**Comment by Yue-Wang-Google** [comment]
btw, could these be nonatomic? I haven't dived into the code deeply.

**Comment by maicki** [comment]
@Adlai-Holler Blocks should be copy as properties, see also the documentation @Yue-Wang-Google linked too ...

@Yue-Wang-Google I think we should add nonatomic cc @Adlai-Holler

**Comment by Adlai-Holler** [comment]
Yeah all these properties should be nonatomic

**Comment by Yue-Wang-Google** [comment]
Done.

**Comment by Adlai-Holler** [comment]
Sweet, thank you for the stream of improvements!

**Pull request merged**
