### PR TITLE
[ASDataController] Restore previous release's behavior to call constrainedSize method serially on one background queue.

### PR DESCRIPTION
**Pull request by appleguy**
New changes to support the nodeBlock... API changed this behavior even for clients that haven't adopted that.  This caused an issue with at least one client, and since there is little value in this being concurrent / it does increase risk for third parties, let's do this.

### CODE REVIEW

**Comment by aaronschubert0** [comment]
@appleguy Awesome!! This fixes the issue that I was witnessing over the weekend. Glad you managed to get to the bottom of this so quickly, appreciate the quick turnaround. That's me all good for 1.9.7.

**Comment by nguyenhuy** [comment]
Can you test against master? We have just landed a fix (https://github.com/facebook/AsyncDisplayKit/pull/1288) that is preferred over this one. Thanks!

**Comment by aaronschubert0** [comment]
@nguyenhuy Will give it a shot!

**Comment by aaronschubert0** [comment]
@nguyenhuy Still solid against master!

**Comment by nguyenhuy** [comment]
Awesome. Thanks, @aaronschubert0!

**Pull request closed without merging**
