### PR TITLE
make inline functions in ASDisplayNodeExtras.h static 

### PR DESCRIPTION
**Pull request by samhsiung**
Resolves linker errors and allows inline functions such as `ASInterfaceStateIncludesVisible` to be used outside of ASDK framework files.

Also according to this:
http://stackoverflow.com/questions/18623392/how-to-write-global-inline-functions-in-objective-c-using-c-syntax

Global inline functions should be static

### CODE REVIEW

**Comment by maicki** [comment]
To be honest I don't really like the idea to expose this functions. We should have public accessors in `ASDisplayNode` where you can get the state of it. @Adlai-Holler thoughts?

**Comment by samhsiung** [comment]
@maicki that sounds good to me. This PR would at least be an upgrade because the inline functions are currently global and accessible, but you will get a linker error if you try to use it.

**Comment by samhsiung** [comment]
Was the point of inlining these functions solely for performance? There might be a very slight performance hit if you wrap the same checks behind a property or method. Originally created this PR due to @appleguy 's suggestion.

**Comment by Adlai-Holler** [comment]
We have a ship task to add the readonly node properties. This header is currently public. If we want to hide these, we should mark the file private – I agree with @samhsiung that these should be static inlines and they're useful for the time being.

@samhsiung could you declare them ASDISPLAYNODE_INLINE?

**Comment by Adlai-Holler** [comment]
Cool thanks @samhsiung !

**Pull request merged**
