### PR TITLE
Disable Text Node Fast Path

### PR DESCRIPTION
**Pull request by Adlai-Holler**
As fast as this is, it's unfortunately crashing sometimes in production, inside `boundingRectWithSize:`.

This also reveals an issue with our classic (slow-path) truncation. Before this diff, both `testFastPathTruncationWorks` and `testSlowPathTruncationWorks` were using the fast-path due to an incorrectly formed test. 

I fixed `testSlowPathTruncationWorks` to actually use the slow path, and it reveals that the text is truncated too early. Investigation reveals that two truncation passes occur. The first pass calculates the correct truncation index, but then the second pass computes the index just before it. This helps us isolate #2140 .

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
Ran the tests locally. This is pretty urgent so I'm going to land it and damn the consequences!

**Comment by jdee** [comment]
This looks like a plausible fix for #2140. I wanted to try it out with master, but I forgot that master is version 2.0. Are there plans to roll this fix into a 1.9.93 or something?

**Comment by maicki** [comment]
@jdee Hey, we are currently hard working on 2.0 and further fixes on the text component of ASDK. Currently there are no concrete plans to roll that into 1.9.93 though.

**Comment by jdee** [comment]
@maicki Thanks for the info. It's a fairly minor bug in a production app that uses ASDK almost exclusively for the UI. Updating to 2.0 looks painful. I guess we won't have much choice but to invest significant effort at some point. I'm sure it will improve a lot of things. Maybe there is/will be a guide or other assistance once we get there.

At least this explains why it works as long as the text includes highlighted links, and why my attempt to insert an invisible link didn't fix anything. Presumably you're checking whether the styling varies and optimizing when it doesn't. But now that I understand that, maybe I can find another workaround in 1.9.92.

Thanks again.

**Comment by maicki** [comment]
@jdee In terms of updating to 2.0. We just updated our documentation to include guides to upgrade to 2.0: http://asyncdisplaykit.org/docs/adoption-guide-2-0-beta1.html hope that helps.

**Pull request merged**
