### PR TITLE
expose relayoutAllNodes at ASCollectionView level

### PR DESCRIPTION
**Pull request by nickvelloff**
The purpose of this PR is to expose `relayoutAllNodes` from `ASCollectionDataController` to `ASCollectionView` to allow us to manually trigger size changes. Particularly useful during an interactive transition where cells are resized by some try of gesture.

### CODE REVIEW

**Comment by nickvelloff** [comment]
cc @nguyenhuy

**Comment by nickvelloff** [comment]
I signed the CLA BTW 😸

**Comment by nguyenhuy** [comment]
At ASDataController level, relayoutAllNode is fine. However, I'm wondering maybe we should have a different name for this API, to be consistent with UIKit naming convention. What do you think about relayoutData or relayoutItems?

Also, should we expose the same API for table view?

**Comment by nickvelloff** [comment]
@nguyenhuy Yes agree on both. I like `relayoutItems` personally.

**Comment by nickvelloff** [comment]
@nguyenhuy ready for review. 

Of course it's the least I can do 👍

**Comment by nguyenhuy** [comment]
LGTM, thanks!

**Comment by nickvelloff** [comment]
👍 Awesome!

**Pull request merged**
