### PR TITLE
[ASRelativeDimensionType] Replace "percent" with "fraction" Where Appropriate

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Because we have the best words! The return of #1179

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
@hannahmbanana @maicki @nguyenhuy @appleguy take a looky-loo?

**Comment by Adlai-Holler** [comment]
Oops the snapshot reference files need renaming. One min

**Comment by maicki** [comment]
In general looks good to me. We just have to be careful as I think this will be an API breaking change?

@Adlai-Holler Is the plan to merge that before 2.0? cc @appleguy

**Comment by Adlai-Holler** [comment]
Since this is so harmless, I think we should leave it open and merge just before releasing 2.0. Should be trivial to rebase as needed. I hate to let it hang around but it kept popping into my mind during the day!

**Comment by hannahmbanana** [comment]
Could we label it with a "breaking API" or "2.0 release" type of label? I think we're going to run into some more of these.

**Comment by hannahmbanana** [comment]
When this gets merged, please uncomment the assertions on lines 23-24 in `ASRelativeDimension.mm`

```
    // TODO: Enable this assertion for 2.0.  Check that there is no use case for using a larger value, e.g. to layout for a clipsToBounds = NO element.
    // ASDisplayNodeCAssert( 0 <= value && value <= 1.0, @"ASRelativeDimension percent value (%f) must be between 0 and 1.", value);
```

**Comment by maicki** [comment]
@Adlai-Holler Can you please rebase your branch. Thanks!

**Comment by hannahmbanana** [comment]
Looks like examples/AnimatedGIF needs to be updated

**Pull request merged**
