### PR TITLE
Remove Deleted Cell Node's View from Cell Immediately

### LINKED ISSUE #2658: [ASCellNode] didExitVisibleState is not called when a visible cell is deleted
Hi guys,

I've had an issue for some time now. I recently upgraded to `master`, but the problem is still here: `didExistVisibleState` (and the previous visibility method for < 2.0) is not called on a visible `ASCellNode` when it is deleted using the `ASCollectionNode` (and previously `ASCollectionView`) method `deleteItemsAtIndexPaths`.
When scrolling, the visibility methods are called correctly. When presenting / pushing another controller, the behaviour is also correct. It only happens when deleting visible cells. Please note that no other data management method is called either (e.g. `clearFetchedData`). As the cell nodes in my application are pretty heavy, I would very much like to be notified when they are permanently deleted.

I made a simple test project that demonstrates the issue: https://github.com/flovouin/ASDK-CellVisibleState
Running the code should output in the console:
```
Adding lots of cells
Removing cells
Showing another controller
Goodbye from cell at index 0!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
Goodbye from a cell that was no longer in the collection!
```
The visibility method for the removed cells is only called once the whole collection disappears. I would expect the following output:
```
Adding lots of cells
Removing cells
Goodbye from cell at index 0!
Goodbye from cell at index 1!
Goodbye from cell at index 2!
Goodbye from cell at index 3!
Goodbye from cell at index 4!
Goodbye from cell at index 5!
Showing another controller
Goodbye from cell at index 0!
```

If you need anything else, don't hesitate to ask.

Cheers,

Flo

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Supersedes #2680 resolves #2658 This has been tested and will get merged after CI.

### CODE REVIEW

**Comment by garrettmoon** [comment]
test this please

**Comment by hannahmbanana** [comment]
test this please

**Comment by appleguy** [comment]
test this please

**Comment by Adlai-Holler** [comment]
The call pattern that this new test case exercises is very interesting and should be investigated. Landing a change this significant, this late in the game for 2.0 is unwise and not justified by the benefits. Punting to 2.0.1 so I can investigate more thoroughly.

**Comment by appleguy** [comment]
10:00:25 Failing tests:
10:00:25 	-[ASTableViewTests testIssue2252]
10:00:25 ** TEST FAILED **

**Comment by Adlai-Holler** [comment]
This shouldn't be landed. Given what the development of the thrash tester has revealed, we should instead change how we drive the cell node visibility bit – either have the range controller remember which nodes _were_ visible and go back and clear them when it picks a new batch, or drive them directly by `willDisplayCell:` and `didEndDisplayingCell:` callbacks. Probably the former.

**Pull request closed without merging**
