### PR TITLE
[ASRangeControllerBeta] Utilize NSMutableOrderedSet to ensure visible items are prioritized.

### PR DESCRIPTION
**Pull request by appleguy**
This also adopts Objective-C generics for the various collections in this class.

### CODE REVIEW

**Comment by appleguy** [comment]
cc @knopp, @nguyenhuy, @tomizmobile - please test it out!  BTW I did detailed performance checking on iPhone 4 and the performance difference is absolutely negligible compared to the other operations in this method.  I can think of a couple different optimizations but they're not worth pursuing at this time as there would be an increase in code complexity.

**Comment by wendylu** [comment]
lgtm

**Comment by knopp** [comment]
@appleguy, seems to work fine for me. Btw. Would something like this fly? https://github.com/facebook/AsyncDisplayKit/pull/1102

**Comment by appleguy** [comment]
Here's the before and after performance comparison - must only use the percentages as the amount of work done in terms of objects is not exactly equal.
screen shot 2016-01-24 at 6 16 36 pm

**Comment by knopp** [comment]
@appleguy, in my case it is about twice as slow, but nothing to write home about. 
screen shot 2016-01-25 at 1 56 05 pm

**Pull request merged**
