### PR TITLE
[ASDisplayNode] Copy Sublayers in recursivelyTriggerDisplayForLayer to Avoid NSFastEnumerationMutation Exception

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Very much like #1421.

### CODE REVIEW

**Comment by appleguy** [comment]
@Adlai-Holler this is an intensely performance sensitive method. I can't immediately think of a use case for changing the layer hierarchy in response to a display call... This method will in fact not even call layout, because that has already occurred shortly before we start the iteration.

Could you share a stack trace for examples of how this enumeration exception can be triggered with a user-interface code pattern that should be supported?

**Comment by Adlai-Holler** [comment]
It's going to take a lot of time to diagnose why the layer tree was getting changed in my use case – the exception doesn't fire until a future loop iteration – but I strongly suspect it's because my ASMultiplexImageNode delegate listens for `didDisplayUpdatedImage` and adds/removes overlay/placeholder content based on what image is actually displayed.

**Comment by appleguy** [comment]
@Adlai-Holler if I can get some details on the stack trace, Or better yet a reproduction case, I'm not opposed to taking this. However, this is a performance critical code path on the main thread and I would like to ensure I understand a plausible scenario in which this would be required.

For example, with the display node call backs for custom drawing, they must be done in a class method and they are called off of main thread entirely. So it doesn't seem like a valid thing to change the layer hierarchy at that time, And the correct fix for a place holder manipulating the hierarchy is more likely adjusting that call rather than copying the tree.

**Comment by appleguy** [comment]
@Adlai-Holler I finally encountered this for the first time.  It is due to some code I would consider incorrect, an outdated manual call to -fetchData that itself triggers adding something to the hierarchy, all triggered by displayWillStart.  That said, all I really wanted before adding this overhead is a concrete stack trace of an example of hitting the issue, and now we have that :).

I'll take this for now, but it would be great to eventually allow deferring displayWillStart just momentarily, until after the iteration, to avoid this high frequency copy -- for the fact that many apps have huge hierarchies and this will happen thousands of times while scrolling.

#0	0x0000000107d8a359 in __32-[ASVideoPlayerNode showSpinner]_block_invoke at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASVideoPlayerNode.mm:496
#1	0x0000000107cb0c64 in -[ASDisplayNode _viewToLoad] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:430
#2	0x0000000107cb19ab in -[ASDisplayNode _loadViewOrLayerIsLayerBacked:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:485
#3	0x0000000107cb1e8c in -[ASDisplayNode view] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:515
#4	0x0000000107cbf57c in -[ASDisplayNode _addSubnodeSubviewOrSublayer:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1520
#5	0x0000000107cbb3fa in __28-[ASDisplayNode addSubnode:]_block_invoke at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1300
#6	0x0000000107cf4a9e in ASPerformBlockOnMainThread at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/Private/ASInternalHelpers.mm:40
#7	0x0000000107cbafa6 in -[ASDisplayNode addSubnode:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1299
#8	0x0000000107d8a05d in -[ASVideoPlayerNode showSpinner] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASVideoPlayerNode.mm:500
#9	0x0000000107d896e8 in -[ASVideoPlayerNode videoNode:willChangePlayerState:toState:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASVideoPlayerNode.mm:423
#10	0x0000000107d8338a in -[ASVideoNode setPlayerState:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASVideoNode.mm:412
#11	0x0000000107d82882 in -[ASVideoNode fetchData] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASVideoNode.mm:336
#12	0x0000000107d1c54d in -[ASNetworkImageNode displayWillStart] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASNetworkImageNode.mm:270
#13	0x0000000107cba798 in -[ASDisplayNode willDisplayAsyncLayer:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1234
#14	0x0000000107c9a076 in -[ASDisplayNode(AsyncDisplay) displayAsyncLayer:asynchronously:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/Private/ASDisplayNode+AsyncDisplay.mm:366
#15	0x0000000107c3b876 in -[_ASDisplayLayer display:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/Details/_ASDisplayLayer.mm:198
#16	0x0000000107c3b7b4 in -[_ASDisplayLayer display] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/Details/_ASDisplayLayer.mm:186
#17	0x0000000107cc32e4 in recursivelyTriggerDisplayForLayer(CALayer*, bool) at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1886
#18	0x0000000107cc34ef in recursivelyTriggerDisplayForLayer(CALayer*, bool) at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1894
#19	0x0000000107cc34ef in recursivelyTriggerDisplayForLayer(CALayer*, bool) at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1894
#20	0x0000000107cc3d23 in -[ASDisplayNode _recursivelyTriggerDisplayAndBlock:] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:1925
#21	0x0000000107cae8bf in __49+[ASDisplayNode scheduleNodeForRecursiveDisplay:]_block_invoke_2 at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASDisplayNode.mm:247
#22	0x0000000107d33dab in -[ASRunLoopQueue processQueue] at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASRunLoopQueue.mm:126
#23	0x0000000107d3340e in __45-[ASRunLoopQueue initWithRunLoop:andHandler:]_block_invoke at /Users/scottg/code/AsyncDisplayKit/AsyncDisplayKit/ASRunLoopQueue.mm:50
#24	0x000000010ab13c37 in __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ ()
#25	0x000000010ab13ba7 in __CFRunLoopDoObservers ()

**Pull request merged**
