### PR TITLE
[Documentation] Improve readability of NS_OPTIONS in Swift

### PR DESCRIPTION
**Pull request by hannahmbanana**

### CODE REVIEW

**Comment by maicki** [comment]
@hannahmbanana If we remove the comments directly from the enums will we loose the Xcode documentation in ObjC if you option-click on it within a source code?

**Comment by maicki** [comment]
@hannahmbanana Can you please also rebase your branch on top of master. It seems like you merged in master a couple of times instead of rebasing.

**Comment by hannahmbanana** [comment]
@maicki - interesting point about losing the option-click documentation. Shall we abandon this idea then?

**Comment by Adlai-Holler** [comment]
I think we should _only_ have the `None` option specified in the main NS_OPTIONS documentation, and only if the behavior of none isn't obvious.

**Comment by Adlai-Holler** [comment]
Nice improvement!

**Pull request merged**
