### PR TITLE
[UIImage+ASConvenience] as_resizableRoundedImage border doesn't respect roundedCorner argument

### LINKED ISSUE #2903: as_resizableRoundedImage border doesn't respect roundedCorner argument
ASDK 2.0.1

When choosing which corners to round with the border option, the border is not taken into account.
i.e

```swift

 UIImage.as_resizableRoundedImage(withCornerRadius: 10.0, cornerColor: UIColor.red, fill: UIColor.yellow, borderColor: UIColor.gray, borderWidth: 0.5, roundedCorners: [.topLeft,.topRight], scale: 0.0)

```
results in the border to still have rounded corners with top right and top left of the corners of the rectangle not clipped.

expected that the corner rounding of the solid object.

### PR DESCRIPTION
**Pull request by hannahmbanana**
Resolves #2903.

#Incorrect:
screen shot 2017-01-17 at 4 03 45 pm

Corrected:
screen shot 2017-01-17 at 4 01 28 pm

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
This PR looks awesome but what the heck @ test failure! No description of what failed, and it says the failure is expected. We should probably open the diagnostic log at `~/Library/Developer/Xcode/DerivedData/AsyncDisplayKit-ggogwdgiwffyeianyojvlczlsubz/Logs/Test/4B292CFF-4A82-41D7-ADB6-2775AEE920FA/Session-AsyncDisplayKitTests-2017-01-17_163504-lW4cbr.log` and see what's up.

**Comment by hannahmbanana** [comment]
@Adlai-Holler - restarting this build didn't seem to help. Do you think pushing an update would cause a different outcome?

**Comment by Adlai-Holler** [comment]
@hannahmbanana Give it a try!

**Comment by Adlai-Holler** [comment]
Well… freaky. Merging!

**Pull request merged**
