### PR TITLE
[ASEditableTextNode] should include insets when calculating size

### PR DESCRIPTION
**Pull request by vadims**

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by maicki** [comment]
LGTM

**Comment by maicki** [comment]
@Adlai-Holler You think that's fine to merge without some sample project?

**Comment by vadims** [comment]
I was going to create a sample project later today.

**Comment by maicki** [comment]
@vadims Awesome, let's wait until that, thank you so much for putting that together!

**Comment by appleguy** [comment]
@vadims appreciate it!  Feel free to modify the EditableText example, which I think might be in examples_extra.  We'll merge this right away afterwards.

**Comment by vadims** [comment]
@appleguy I updated the sample I used for the last PR

**Comment by appleguy** [comment]
Fantastic! Michael should be able to run this tomorrow and get it merged.

**Comment by maicki** [comment]
Run it and it looks good to me will merge now. Thank you @vadims for this work!

**Pull request merged**
