### PR TITLE
Remove Support for iOS 7

### PR DESCRIPTION
**Pull request by Adlai-Holler**
- Raise deployment target to iOS 8.
- Remove static library target – simplifies our project config to be framework-centric a la IGListKit.
- Add modern Obj-C annotations to `ASTraitCollection`.

@garrettmoon @appleguy @maicki @nguyenhuy

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
cc #2928

**Comment by Adlai-Holler** [comment]
Jenkins test this please

**Comment by Adlai-Holler** [comment]
Jenkins test this please

**Comment by Adlai-Holler** [comment]
Jenkins test this please

**Comment by garrettmoon** [comment]
test this please

**Comment by garrettmoon** [comment]
test this please

**Comment by Adlai-Holler** [comment]
retest this please

**Comment by Adlai-Holler** [comment]
Retest this please

**Pull request merged**
