### PR TITLE
[ASLayoutSpec] Add new .flexGone property to more easily trigger omitting nodes from a layout.

### PR DESCRIPTION
**Pull request by bimawa**
Ok i merge last master state. And ready for contribute this work correctly.   

-------
facebook/AsyncDisplayKit#1640

### CODE REVIEW

**Comment by levi** [comment]
@bimawa this is great, thanks for putting it up as a PR. As a suggestion of the core behavior of flex gone, I'd recommend simply checking for the property being true at ASLayout flatten time. If the test passes, you can simply exclude it from the final ASLayout sublayout hierarchy.

The other main question we should answer is do we want the ASLayoutable with FlexGone enabled to still calculate it's layout spec? Generally seems like we should forego it and rebuild the entire ASLayout tree that was disabled when the property was YES. If that's the case, you can reduce the footprint of flex gone by checking if the property is YES in an ASDisplayNode's calculateSizeThatFits: and returning a zeroed out ASLayout instead of entering measureWithSizeRange: on the layoutables and having to provide a bunch of boilerplate guard statements.

**Comment by bimawa** [comment]
@levi Thank you Levi for review. Yes i think similar, and i worry about `Implicit Hierarchy Management` just if we have `gone = YES` we must remove node from supperNode for better? 

>FlexGone enabled to still calculate it's layout spec? 

Yes i think we not need spend a resources on calculation. 
So. I try find way how i can check  ASLayout flatten time. And modify PR.

**Comment by bimawa** [comment]
pls Travis! Let me home!

**Comment by bimawa** [comment]
@levi i need help :( why Travis so angry?

**Comment by levi** [comment]
@bimawa looks like the unit tests are failing. Try running the tests locally to identify what is not passing.

**Comment by bimawa** [comment]
@levi  is't your code `sublayouts:nil`. I'n just add sublayers from context. And i don't sure so it fully correct. Pls. check.

**Comment by appleguy** [comment]
@bimawa thanks for your work on this!  Next time though, don't curse in commit messages :).  Those last a long time...

**Comment by bimawa** [comment]
@appleguy oh .. sry for this, it's all my weak English.

**Comment by maicki** [comment]
@levi @appleguy What do you guys think of having that behavior based on the `hidden` property of an `ASDisplayNode` instead of introducing a completely new property that is not in the flex box standard?

**Comment by levi** [comment]
@maicki I was thinking that too, but would be unexpected to see a node not in the hierarchy for a seasoned iOS dev. Introducing a separate property here would be the way to go. CSS makes a similar distinction with Display: none; and visibility: hidden;

**Comment by appleguy** [comment]
I think it is a good idea to suggest, Michael. However, this behavior would definitely break some existing apps, and I agree with Levi that there would be at least some developers confused by a difference compared to the equally named Apple framework property. 

I'm not sure that the name used in the current patch is the best one, but we should probably introduce a new name besides hidden.

**Comment by bimawa** [comment]
Guys, when researching a code, i saw `flattened` property with behaviour similar like `hidden`.

**Comment by maicki** [comment]
Yeah after looking into how Auto Layout treats hidden views, Auto Layout still considers the view also if it's set to hidden.

**Comment by bimawa** [comment]
Yea `hidden` property very similar like `alpha` :)

**Comment by maicki** [comment]
`flatten` property has nothing to do with `hidden` and is not for public usage. Furthermore this property will be not public anymore in the near future.

**Comment by bimawa** [comment]
Ouch ) thanks for info. Take it notice.

**Comment by eanagel** [comment]
I know there has been a lot of discussion on this topic, so maybe I'm rehashing discussions that people have already had on slack here, but I thought I'd pass on my thoughts in case they could be useful.

1. As someone who has implemented some non-trivial layout code, I see how something like this could be useful. Our messaging app has many (many) optional elements and at times getting the logic around the different use cases  and combinations can be tricky. Being able to return a layout spec that included all possible nodes with some of them effectively "gone" could be helpful.
2. I really like the declarative nature of layout specs as we currently have them. It seems to me that making this new property updatable outside `layoutSpecThatFits:` would break this model (is that the proposal?) I'd suggest that we keep the declarative nature and not support changing the value outside `layoutSpecThatFits:`. For my use cases, it would work perfectly. (I typically call `setNeedsLayout` whenever a value changes that effects layout anyway.) The downside of this is it might cause extra overhead at times (you might not technically need to re-create the layout tree of you are only toggling on of these values), but there is a simplicity and clarity I really like about it. Plus, the layout happens on background threads which helps minimize the impact.
3. How does this work if a layout has a single child and this property is enabled for the child? What happens to the parent layout? Does the flattening handle this somehow? Seems like you could get into some really weird states with something like an `ASOverlayLayoutSpec` where the child was set to `gone` Would we correctly handle this case? What if the overlay was set to `gone`?
4. `flexGone` seems like a non-obvious name (partially because of the `flex` prefix), how about `flexIgnore` instead? or maybe even be more clear and go for `flexIgnoreLayout`?

**Comment by bimawa** [comment]
@appleguy #953 not related with it.

**Comment by bimawa** [comment]
Guys what u think about "Implicit Hierarchy" my property might be included in it or not?

**Comment by Adlai-Holler** [comment]
After more internal discussion about this solution, we're going to keep evolving the layout system to be more declarative and avoid adding more state to the layout properties of nodes. Thanks @bimawa for proposing this and further thanks to everyone for the clear and thorough discussion around it.

**Comment by bimawa** [comment]
@Adlai-Holler Ok. Thanks!

**Comment by Adlai-Holler** [comment]
@bimawa Yes

**Pull request closed without merging**
