### PR TITLE
Move ASTableView & ASCollectionView data fetching to background thread

### PR DESCRIPTION
**Pull request by tanliboy**
Add "collectionViewLockDataSourceForDataUpdating" and "collectionViewUnlockDataSourceForDataUpdating" for enable data fetching from background thread.

### CODE REVIEW

**Comment by phatmann** [comment]
This looks great, thanks for the fast turnaround! I will pull this and try and it out tomorrow.

**Comment by phatmann** [comment]
So far this change is working great. No issues and the main thread is not blocked while nodes are being created.

**Comment by secretiverhyme** [comment]
Very cool!  Some thoughts:

`ENABLE_ASYNC_DATA_FETCHING` and `_asyncDataFetchingEnabled` seem redundant, and the way `BEGIN_DATA_FETCHING` and `END_DATA_FETCHING` convert method contents into blocks is hacky.  Can we remove all three `#define`s in favour of a method that explicitly takes a block and processes it asynchronously if async fetching is enabled?  So,

```objective-c
- (void)method
{
  BEGIN_DATA_FETCHING
  /* do stuff */
  END_DATA_FETCHING
}
```

would become

```objective-c
- (void)method
{
  [self performDataUpdate:^{
    /* do stuff */
  }];
}
```

ASTableView asserts that its data source implements lock & unlock methods, but ASCollectionView does not.  Instead of adding a new initialiser for both of these classes and juggling these assertions, can we check whether the data source implements both lock & unlock methods at the time `-setDataSource:` is called, and use that to set ASDataController's `_asyncDataFetchingEnabled` property?  This way simply implementing those two methods will be enough to opt into the new behaviour.

Can we remove `ForDataUpdating` from the new delegate method names?  `-tableViewLockDataSource`, `-collectionViewUnlockDataSource`, and so on are easier to read.

Typo:  `asyncDataSouceLocked` should be `asyncDataSourceLocked`.

Overall this is a fantastic improvement.  We should update the Kittens sample project to use these new delegate methods, and update the documentation to clearly advise that you use these methods ("WARNING:  ASTableView and ASCollectionView performance will be adversely impacted if you don't implement `-...LockDataSource` and `-...UnlockDataSource`!").  We should also consider making these data source methods non-optional, given how critical this change is.

**Comment by phatmann** [comment]
After further testing, I am unhappy to report that this pull request does not solve my original problem described in #288. I have an AKTableView with 1000 nodes using async data loading. Each node has a close button that removes the node from the table. If I tap a node's close button immediately after the nodes appear, the tapped node is not removed for several seconds. If a wait a few seconds after the nodes appear, then tapping the close button removes the node immediately. In either case, subsequent taps on a node's close button remove the node immediately. In short, when the nodes first appear, the table is not responsive. Our assumption has been that this lack of responsiveness is due to the overhead of loading nodes. Either this assumption is wrong, or this pull request does not solve the issue. I will do more profiling to see what is going on.

If we cannot solve this issue in the near term, then I would like to consider re-opening #288, which requested that there be a way to determine when the table is actually fully loaded and responsive.

**Comment by phatmann** [comment]
I just did some profiling on my iPhone 5S. Over 70% of the load time is spent in ASDisplayNode's `measure`. My tap on the close button is recognized immediately, so the UI is responsive during this load time, which is expected since the measuring takes place on a background thread. However, there is a delay of several seconds between the tap and when the node is removed from the table. After all the measuring is done, subsequent taps remove the node immediately, so the measuring is what is causing the delay. My node has a fairly simple layout; more complex nodes would have even more delay.

So the issue is that visible nodes cannot be removed until _all_ nodes are measured. Should I file a new issue for this?

And back to #288 again: if we cannot solve the issue with the measuring cycle blocking node removal, I would like a way to know that all the nodes have been measured, so I can accommodate removal delays in the UI; e.g. show an activity indicator during the slow removal.

**Comment by tanliboy** [comment]
Yes, this change would not solve that issue.
We are doing the editing in async mode.
For the initialization, we inserted 1000 nodes in batches. Supposed we grouped it into 50 operations, each operations will insert 20 nodes into table. These operations are queued in a serialized dispatch queue. If we want to remove a node, it will be pushed into the queue and not be executed directly.

**Comment by tanliboy** [comment]
Yeah, it sounds a good  idea to add a function call to tell the data source that all operations has been take effect.

**Comment by phatmann** [comment]
I filed #309 to cover the node removal delay.

**Comment by phatmann** [comment]
@tanliboy, thanks for the explanation. Can we re-open and rename #288 (or file a new issue) to request a notification that all operations have been completed?

**Comment by tanliboy** [comment]
@phatmann , hmm, if we could solve the issue #309 , we may don't need the notifications any more.
I will think about that problem and update there.

**Comment by phatmann** [comment]
For the readers at home just joining us:

* #309 will be largely taken care of by #258 
* If #309 is solved, then #288 might not be so important

So if we can knock off #258 lots of good things start happening :-)

None of this has much to do with this issue, so I will make a similar post at #309 and continue the discussion there.

**Pull request merged**
