### PR TITLE
[Layout] Unify ASRelativeSizeRange and ASSizeRange

### PR DESCRIPTION
**Pull request by maicki**
### Goal:
To simplify sizing within ASDK this PR will rename `ASRelativeSizeRange` to `ASSizeRange` and remove the old implementation of `ASSizeRange`.

### TODOs:
- [x]  Unify `ASRelativeSizeRange` and `ASSizeRange` to just `ASSizeRange`
- [x] Rename `ASRelativeDimension` to `ASDimension`
- [x] Add better helper functions to create `ASSizeRange`
- [x] Add better helper functions to get information out of `ASDimension` and `ASSizeRange`
- [x] Add assertions for API that only supports `ASSizeRange` with `ASDimensionTypePoints`
- [x] Adjust example projects

**Please note:**
This is a huge API change that will basically have an effect of all apps that are written with ASDK

**This PR is one of the initiatives to make the Layout API more clear. Every feedback is more than welcome!**

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
I'm good with landing this once Pinterest is compatible. @hannahmbanana ?

**Comment by keleftheriou** [comment]
test this please

**Comment by keleftheriou** [comment]
Build triggered. sha1 is merged.

**Comment by keleftheriou** [comment]
Build started sha1 is merged.

**Comment by keleftheriou** [comment]
Build finished.

**Comment by keleftheriou** [comment]
test this please

**Comment by maicki** [comment]
@appleguy @Adlai-Holler @garrettmoon @levi  Ready for review

**Comment by maicki** [comment]
Closing this PR. It will be addressed by #2110.

Just unifying `ASRelativeSizeRange` to `ASSizeRange` is not the right approach, as we have to add a lot safeguards in case an `ASSizeRange` would include fraction values but only points are allowed. This means we have to push certain checks to runtime instead of relying on compile time checks. 

Furthermore it would make the APIs actually more confusing. Developer would have to fight with how a `ASRelativeSizeRange` works to be able to create them. Instead in #2110 we going a different route and remove the `ASRelativeSizeRange` completely in favor of a easier API to a set a size to an `ASLayoutable`.

**Pull request closed without merging**
