### PR TITLE
[ASVideoNode] issue #1782 Placeholder images are replaced by blanks during loading

### PR DESCRIPTION
**Pull request by gazreese**
Now checks the .URL property of the parent class as well as the .image to ensure that new placeholders aren't generated.

Please see https://github.com/facebook/AsyncDisplayKit/issues/1782 for details.

### CODE REVIEW

**Comment by hannahmbanana** [comment]
@Xinchi is going to try this out and let us know if it fixes his issue. Right? :)

**Comment by hannahmbanana** [comment]
This failed because i was using the old .travis.yml / build.sh file - it's trying to build mode = examples, when now we have examples_pt1, etc. 

I reran the build, but I'm not sure if that will resolve it or if we need to do something else.

**Comment by hannahmbanana** [comment]
@Xinchi: were you able to test this out?

**Comment by hannahmbanana** [comment]
@gazreese: this build will always fail because it is using our old script. Could you rebase please?

**Comment by gazreese** [comment]
@hannahmbanana  Looks good now, could you please take a look? Thanks!

**Comment by Adlai-Holler** [comment]
@gazreese Another great change. I noticed that the image is being reset because when we first call `generatePlaceholderImage` the AVAsset has no tracks and so we call completion with `nil` and clear the image. This is certainly not an intended behavior.

I think the ideal behavior here is to clear self.image in -setAsset: or -clearFetchedData _if it was automatically set_ but otherwise the node itself should never `self.image = nil`. Thoughts @gazreese @appleguy ?

Thanks again for this and all your other well-made contributions lately. Landing this immediately!

**Pull request merged**
