### PR TITLE
Implement "space between" and "space around" justify content options for stack layout

### PR DESCRIPTION
**Pull request by nguyenhuy**
## Author: Thanh Huy Nguyen

The specs of these options can be found here: http://www.w3.org/TR/css-flexbox-1/#valdef-justify-content-space-between

For both options, I couldn't find a documented way to handle the case when there is a remaining space after spacing division. So I made them up based on what I think are "sensible" behaviours.

Once this diff is landed, there will be no need to use a flexible spacer between children to push them away from each other. cc @levi @hashemp206, @lappp9.

### CODE REVIEW

**Comment by nguyenhuy** [comment]
And these options have not been implemented in CK yet. Thinking about contributing back :)

**Comment by levi** [comment]
This is awesome, Huy. Something I've been wanting since I started using stack layouts.

**Comment by smiLLe** [comment]
Awesome :) i was always missing space-between in CK.

**Comment by aaronschubert0** [comment]
Awesome! Looking forward to this.

**Comment by appleguy** [comment]
@nguyenhuy This is REALLY cool!  Huge improvement in the flexibility of the stack, and solves several awkward layouts we have worked around at Pinterest.  This really helps 2.0 be a fully featured release.

Sorry it took two weeks for me to review — this diff is the last thing I've caught up to after falling behind on Issues and PRs.  Phew, hopefully I can focus until 2.0 is GM'd...

**Comment by lappp9** [comment]
dude, @nguyenhuy, this will be way better!

**Comment by nguyenhuy** [comment]
@appleguy Thank you for accepting this diff. And don't worry about the delay :)

Very happy to know that my work is appreciated by others. Please make the most of ASDK, guys.

**Pull request merged**
