### PR TITLE
[ASCollectionView] layoutInspector can be nil'd at anytime making flags unsafe

### PR DESCRIPTION
**Pull request by garrettmoon**
Hopefully addresses #2471 

I'm actually not sure if even this is safe as layoutInspector could
be nil'd out *after* we check it here…

### CODE REVIEW

**Comment by garrettmoon** [comment]
Yeah, that seems better, will update.

**Comment by garrettmoon** [comment]
Thinking about this a bit more, is there any concern about the site effect of creating a layoutInspector if there isn't one on every call to scrollableDirections?

**Comment by Adlai-Holler** [comment]
@garrettmoon We won't – in the getter we will only ever create one default layout inspector.

**Comment by garrettmoon** [comment]
test this please

**Pull request merged**
