### PR TITLE
Fix failing tests related to ASDisplayNode name

### PR DESCRIPTION
**Pull request by nguyenhuy**
#773

### CODE REVIEW

**Comment by nguyenhuy** [comment]
Since this PR contains a revert commit. I think it's easier to review commits individually.

cc @Adlai-Holler

**Comment by appleguy** [comment]
Wow, cool :)  Will land as soon as the tests pass

**Comment by Adlai-Holler** [comment]
Nice! Thanks again @nguyenhuy

**Comment by nguyenhuy** [comment]
You're welcome :)

**Pull request merged**
