### PR TITLE
[Layout] Remove legacy layout validation code

### PR DESCRIPTION
**Pull request by maicki**
As a lot changed recently in the layout code I think it's time to remove the legacy layout validation code and come up with a better solution.

In our effort to remove legacy and mostly confusing code let's get rid of it now.

### CODE REVIEW

**Comment by garrettmoon** [comment]
I agree, tests feel like a better way to validate layout.

**Comment by levi** [comment]
👍 validation can be done statically with this new layout style API.

**Comment by appleguy** [comment]
test this please

**Comment by appleguy** [comment]
test this please

**Pull request merged**
