### PR TITLE
Tint color for ASButtonNode

### PR DESCRIPTION
**Pull request by lappp9**
This is an implementation of the UIButton's behavior when an image for one of its states is in template mode.

I figured it would be easy to just set up the imageNode's imageModificationBlock to apply the tint color to its image when a particular image was in template mode.

As I'm typing this up, I'm thinking maybe using the image modification block for this implementation is a bit wasteful?  Instead, it might be good to just use the underlying function to make a tinted version of the image for that state if the provided image is in template mode.  You would end up needing to loop through and recreate new tinted image when the tint color was changed though.  Not sure if one way is preferable.

I'll open the PR and maybe change the implementation depending on if anyone has an opinion one way or the other.  

https://github.com/facebook/AsyncDisplayKit/issues/2533

### CODE REVIEW

**Comment by lappp9** [comment]
@hannahmbanana @Adlai-Holler @garrettmoon  not sure if this is useful but I opened it a little while back.  If that refactor sounds worthwhile I could do it first

**Comment by appleguy** [comment]
Very cool!!  I think we should support it on base ASImageNode for sure, and that it would primarily see usage in ASButtonNode.  Will review when I get a chance in the next few days.  Thanks for working on this :)

**Comment by lappp9** [comment]
Ah good point, ok cool, I'll move the logic to ASImageNode and you can let me know if there's anything else off about it!

**Comment by rainypixels** [comment]
@appleguy Any ETA for merging this PR to master? Asking for a friend. 😄

**Comment by lappp9** [comment]
@rainypixels  I need to change some stuff around before it'll be ready to merge.  I'll try to update it this next week!

**Comment by rainypixels** [comment]
@lappp9 That would be excellent! Looking forward to it.

**Comment by Adlai-Holler** [comment]
Jenkins, add to whitelist

**Comment by Adlai-Holler** [comment]
Closing this due to inactivity. @rainypixels feel free to open a similar diff if this feature is very valuable to y'all. Cheers!

**Pull request closed without merging**
