### PR TITLE
Fix self capture in ASCollectionNode

### PR DESCRIPTION
**Pull request by austinlouden**

### CODE REVIEW

**Comment by garrettmoon** [comment]
@austinlouden you cool with this one instead https://github.com/facebook/AsyncDisplayKit/pull/2645 ? @nguyenhuy also was fixing at the same time :)

**Comment by garrettmoon** [comment]
Actually I think this is the correct patch. Can you apply the same thing to `ASTableNode`?

**Comment by nguyenhuy** [comment]
@austinlouden Thanks for working on this!

**Comment by garrettmoon** [comment]
test this please

**Pull request merged**
