### PR TITLE
ObjectiveC: Nullability, Lightweight Generics

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Killer framework! This PR updates the public API Objective-C for Xcode 7 so the framework integrates with Swift better plus adds some compiler checks.

### CODE REVIEW

**Comment by levi** [comment]
Thanks for this, @adly-holler. I was just adding these this morning and you beat me to it :). Be sure to update the .travis.yaml to support the syntax additions: `osx_image: xcode7`.

**Comment by adly-holler** [comment]
Ah! Thanks @levi , done and done!

**Comment by SRandazzo** [comment]
yyyaaaaassssssss!!!! :+1: so much on this! Thanks

**Comment by adly-holler** [comment]
@appleguy If this is too big a change for one external PR, I'd be glad to target a separate branch so others can work on it too

**Comment by appleguy** [comment]
Hey @adly-holler — love your enthusiasm, as I was starting to use this syntax in some of my own work :).  I was hesitant to change the build system configuration right before the NSSpain announcement of 2.0.  It's still not showing a clean build, but let's retry it and see if we can get it in!

**Comment by adly-holler** [comment]
@appleguy Sweet! I got it to the point where it'll build on Travis, but now some tests are failing because of missing implementations of category properties like `[_ASDisplayLayer asyncdisplaykit_isAsyncTransactionContainer]: unrecognized selector`. I added an implementation for one of them, and then it crashed on a different one. 

I don't quite understand how these methods were ever getting implemented in the first place. All I can find is `@dynamic [name]` specifiers with no implementation code in sight. Any pointers?

**Comment by appleguy** [comment]
@adly-holler if you roll back your commits, does it start building?  Maybe try submitting a PR with the Xcode 7 travis build image alone, without adopting any new language features, and see if that has the same issue?

I'm pretty sure ASDK builds with Xcode 7, but perhaps not on Travis.

**Comment by appleguy** [comment]
This change allowed me to build & run unit tests locally with Xcode 7 Beta 5.  Downloading the final version, but it may not finish before I get on the plane tomorrow (going very slowly on hotel internet).

https://github.com/facebook/AsyncDisplayKit/pull/670

**Comment by adly-holler** [comment]
The build is OK but the tests are failing at runtime because it can't find implementations for category properties like `CALayer.asyncdisplaykit_node`. And neither can I!

**Comment by appleguy** [comment]
@adly-holler so I was actually running Xcode 7 on the plane for at least 10 hours today, and called this method in the debugger dozens of times while working on the Synchronous Concurrency stuff.  I didn't look carefully for the error, in particular if it only occurs while running unit tests, but really didn't encounter it.  Do you see it on master if you are doing a regular build-and-run (debug simulator), or build-and-profile with time profiler?

**Comment by appleguy** [comment]
@adly-holler go ahead and resolve the merge conflicts and let's do what it takes to get this landed tomorrow.

**Comment by appleguy** [comment]
(stupid American Airlines managed to lose my luggage, too.  I could only deal with ASDK for 10 of the 15 plane-hours, but after at least 5 more in airports due to their delays, one would hope the bags would at least make it!)

**Comment by adly-holler** [comment]
@appleguy Interesting… on my local machine, on both `master` and this branch, using build-and-run on simulator 8.4 and 9.0, the same code path works fine. The code I used was:

```objectivec
// make it visible
@interface CALayer (ASDisplayNodeInternal)
@property (nonatomic, assign, readwrite) ASDisplayNode *asyncdisplaykit_node;
@end

// [later]

ASDisplayNode *node = [ASDisplayNode new];
CALayer *layer = node.layer;
assert([NSStringFromClass(layer.class) isEqualToString:@"_ASDisplayLayer"]);
__unused ASDisplayNode *nodeAgain = layer.asyncdisplaykit_node;
```

Accessing `_ASDisplayLyer.asyncdisplaykit_node` is an instacrash in the unit tests.

**Comment by levi** [comment]
Any progress with 7.1?

**Comment by appleguy** [comment]
You can try it yourself too, but just like the Beta that I’d tested before, it still has the same issue.

I’ve pinged Apple about it around the time that 7.1 GM’d, but haven’t heard back beyond acknowledgement of the bug.

		— Scott

**Comment by levi** [comment]
Still failing -__-

**Comment by appleguy** [comment]
@Adlai-Holler what you're talking about is not building & running the Tests, right?  Just building the framework / an app?  Yes, it quite clearly does work to compile the framework and have it run correctly under Xcode 7.x, and the issue (and Radar bug description) is definitely specific to the tests environment.

I wouldn't be surprised if there's a workaround for this, but I can't think of one that is less dramatic than eliminating reliance on @dynamic properties entirely.

**Comment by appleguy** [comment]
Sadly there is zero traction whatsoever on the Apple issues, so it is going to take months to land this.  I am going to close the PR until we are on Xcode 7, and then reopen.

**Comment by appleguy** [comment]
I worked around Apple's frustrating, still-unfixed bug with @dynamic properties on CALayer by avoiding use of them.  It's a suboptimal solution as we lose certain capabilities, but I'm excited to get this in.  A truly happy Christmas 2015, lol!

https://github.com/facebook/AsyncDisplayKit/pull/994

**Comment by appleguy** [comment]
Now superseded by #995 as this couldn't be merged with master.  Getting close to 1000!

**Pull request closed without merging**
