### PR TITLE
[ASViewController] Don’t use the view of the root node for the view of the ASViewController

### PR DESCRIPTION
**Pull request by maicki**
Due to the fact we use an `ASDisplayNode`’s view as view of the `ASViewController` we ran into a couple of problems in the past as well as we have a couple of open issues (see issues below). Especially around sizing and layout, we work against UIKit instead of working with UIKit.

### Changes
- We should change from having the view of the display node as ASViewController.view to add the node as subview to the ASViewController.view
- Stretch the node always the full size of the ASViewController.view in the layout pass
- Remove `nodeConstrainedSize`

### Open Questions
- `ASViewController` containment: Big question mark and that's the reason why we have this PR still in development stage is the handling of view controller containment. A good example is within here: https://gist.github.com/maicki/45a33341af35d6a04dbb8df7db13f42e . The problem within here is that the node hierarchy will not reflect the view hierarchy anymore. @Adlai-Holler, @appleguy any thoughts on it?

### Related issues
- ASViewController/ASPagerNode layout bug since version 1.9.81 https://github.com/facebook/AsyncDisplayKit/issues/1949 (fixed)
- ASViewController does not resize when contained in a Container View https://github.com/facebook/AsyncDisplayKit/issues/2085 (fixed)
- [ASViewController] Accessing vc.node.view doesn't go through ViewController's -loadView. (fixed) https://github.com/facebook/AsyncDisplayKit/issues/2350
- Accepts edgesForExtendedLayout without any hacks (fixed without special code) https://github.com/facebook/AsyncDisplayKit/pull/2123
- [ASViewController] Regression causing layout issues when presenting a portrait-only view controller while in landscape (fixed without special code) https://github.com/facebook/AsyncDisplayKit/issues/2213
- [ASViewController] iOS 8 + UIWindow rotation problem (fixed without special code) https://github.com/facebook/AsyncDisplayKit/issues/1905
- [ASViewController] Modal presented ASViewController don't rotate on iOS 8.3 (fixed without special code) https://github.com/facebook/AsyncDisplayKit/issues/1810

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
Nice! This essentially resolves https://github.com/facebook/AsyncDisplayKit/issues/2350 as well, since now using `vc.node.view` and `vc.view` interchangeably is no longer valid. Some users may misunderstand this, but I think that's acceptable.

**Comment by appleguy** [comment]
@maicki once you resolve the merge conflicts, excited to see this one green! √

**Comment by maicki** [comment]
@appleguy Rebased and merge conflict resolved

**Comment by maicki** [comment]
@Adlai-Holler Some answers:
- We don't rely on a `setNeedsLayout` call. What is your thinking behind it?
- It should work with `initWithViewBlock:` nodes as the view will be assigned as view to the node. Layout does not rely on any `setNeedsLayout` call anymore. We call `layoutThatFits:` in `viewWillLayoutSubview` or if the `constrainedSize` will change due to frame changes we use the frame within the node to layout the subnodes if a layout pass happens.
- I changed to set the autoresizing mask to `[.FlexibleWidth, .FlexibleHeight]`. We still call `layoutThatFits:` in `viewWillLayoutSubviews` to prepare the node for the layout pass otherwise we just delay the measure pass to the layout pass. It should not have any overhead as if the frame didn't change it's a no op. We could push this layout async in the future, but I actually already plan to look into that doing it within `ASDisplayNode` by default.

**Comment by Adlai-Holler** [comment]
Hmmm what if we keep the current behavior, but always use exactly `view.bounds.size` as nodeConstrainedSize? It seems like `UIViewController` is designed to naturally support you providing your own view, as long as you don't manually change its frame.

**Comment by appleguy** [comment]
@Adlai-Holler @maicki I think that last statement is correct:

- UIViewController is most definitely designed for users providing their own view.  This is of course what -loadView is for.
- This works with UITableView, UICollectionView, but also many other custom view subclasses.  It should work with _ASDisplayView too :).
- Indeed, the main difference is sizing / layout.  UIViewController expects to set the bounds on the view, just like the parent of a UIView would; also just like a regular UIView, it should never change its own bounds size.

**Comment by Adlai-Holler** [comment]
Superseded by #2653

**Pull request closed without merging**
