### PR TITLE
[ASVisibility] Don't change the range mode if the node was not loaded yet

### PR DESCRIPTION
**Pull request by maicki**
Changing the range mode needs to access the view within the node. If the view was not loaded at this point it will trigger a view load, but that's not necessarily wanted so prevent changing it if the node is not loaded yet.

cc @garrettmoon Garrett does this change makes sense or do you have other ideas around it?

### CODE REVIEW

**Comment by garrettmoon** [comment]
Should this be handled at the <ASRangeControllerUpdateRangeProtocol>node level instead? I.e. prevent it from loading the node based on this?

Could we, for example, only schedule a rangeUpdate if the node isn't loaded?

**Comment by maicki** [comment]
Yes we could add that check on the node level instead of the `ASViewController` level, but what if we really want to force the range update on the node, that was the thinking behind it.

**Comment by garrettmoon** [comment]
Could the range update happen on node load? I honestly don't know the answer, but in there a reason to force the node to load to update the range? Or would it be better to update the range and have it applied when the node loads?

**Comment by maicki** [comment]
We could have a pending state as in `ASDisplayNode` for the range mode and on node load we could apply it.

So logic would be:
1. If node is loaded just apply
2. If node is not loaded save as pending state
2.1 If node is loading apply pending state

This could also work for range parameter adjustments

**Comment by garrettmoon** [comment]
That seems like the right solution to me!

**Comment by maicki** [comment]
@garrettmoon Added a pending state in ASCollectionNode and ASTableNode for the range mode

cc @Adlai-Holler @appleguy

**Comment by garrettmoon** [comment]
LGTM!

**Pull request merged**
