### PR TITLE
[Layout] Remove ASLayoutValidation

### PR DESCRIPTION
**Pull request by maicki**
## This PR will be replaced by: #2172

`ASLayoutValidation` was never really thought through. There are other ideas / solutions on the horizon that will come in the near future, so we should just get rid of that code.

@Adlai-Holler @garrettmoon @appleguy

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
I'm cool with removing this but I don't know much about the history there. Let's have @appleguy weigh in

**Comment by maicki** [comment]
@appleguy @levi any thoughts?

**Comment by levi** [comment]
Seems early to remove this if we don't have a replacement.

**Comment by Adlai-Holler** [comment]
Superseded by #2172

**Pull request closed without merging**
