### PR TITLE
[WIP] Async video player

### PR DESCRIPTION
**Pull request by wokalski**
This pull request contains async video player. It follows #2513. 

In short, after merging it, there should be `ASVideoNodeBeta` with satisfactory (more on that below) set of features.

- [x] Play/pause
- [x] Setting playback rate
- [ ] Delegate
- [ ] Seeking (tricky - a naive implementation causes a ~second long delay)
- [ ] `ASVideoNodeBeta` implementation (planning to copy-paste `ASVideoNode` for most part)
- [ ] Sound (tricky - timing)
- [ ] Thumbnail generation
- [ ] Videos from remote sources

I marked two of them _tricky_. 

- The issue with seeking is that in the naive implementation, I would rebuild the whole reader stack. It results in an awful (~1 second) delay. I think it's resolved internally both at [FB](https://github.com/iAdam1n/App-Headers/blob/0ffb7404b66881bcb18be8636fd121ad7c82f6b1/Facebook/v62.0/FBRCTVideoReader.h#L38) and [Instagram](https://github.com/snower0428/jb/blob/5ccb15ae99b9bffd15fc961ad27b9953b42b8eec/Dump/instagram.h/IGVideoReader.h#L27) so feel free to give me a hint 😉.
- Audio - similarly as above. I am not an `AVFoundation` expert so I'm looking for best ways to sync audio with videos.

---

Alternatively we might not implement any of the tricky ones because the main use case for this is 60 fps scrolling. You usually don't need audio and additional playback controls for that.

Please do let me know your thoughts and I'll proceed accordingly.

### CODE REVIEW

**Comment by kharmabum** [comment]
@wokalski have any ideas on where to start for support for remote sources? I can try tackling it.

**Comment by wokalski** [comment]
Good question. It depends on the kind of stream you want to support. There's a lot information online about it if you look for `AVSampleBufferDisplayLayer`. Feel free to take over this PR. I'm not going to have time to finish it, yet I think it'd be super useful for some people.

**Comment by appleguy** [comment]
@wokalski wow, cool, thanks for thinking to contribute this!  We will probably have to close this out, but I think we could open an issue to hold onto a link to the PR so it can be revived when someone next wants to invest in it.

**Comment by wokalski** [comment]
Yeah, I am not going to have time for this but from what I've seen there's some demand for this feature.

**Pull request closed without merging**
