### PR TITLE
[ASCollectionView] Move constrainedSizeForNodeAtIndexPath from the DataSource to the Delegate

### PR DESCRIPTION
**Pull request by tberman**
Small change w/ some associated cleanup, this feels like a delegate method, not a datasource method.

### CODE REVIEW

**Comment by levi** [comment]
Thanks for this, @tberman! Definitely a needed improvement for an API that hasn't seen much light.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by appleguy** [comment]
@tberman @levi interesting idea. Technically, this is a breaking API change, Although it might be rare to find an application which sets these variables differently. Did you have a chance to look at the table API to make sure there is not an equivalent modification?

Welcome, @tberman !

**Comment by maicki** [comment]
We have to be careful with this change as @appleguy points out these are breaking API changes e.g. in Pinterest we would have to rewrite a couple of places to integrate this change.

**Comment by tberman** [comment]
> @tberman @levi interesting idea. Technically, this is a breaking API change, Although it might be rare to find an application which sets these variables differently. Did you have a chance to look at the table API to make sure there is not an equivalent modification?

Nothing that looked similar to me.

I came across this and felt it was strangely placed when I was implementing a common data source that did some more intelligent animated insertion and diffing and realized that this was implemented on the data source and the delegate, and it felt *very* out of place, which is what drove the change.

Curious on breaking changes what the policy is?

**Comment by maicki** [comment]
Agree that it's kind of out of place if you look into UITableView / UICollectionView data source and delegate protocols.

If we want to integrate the change we would deprecate it in versions < 2.0 and planning to remove all deprecations / breaking API changes with 2.0.

Look into the `ASTextNode (Deprecated)` category for an example.

**Comment by tberman** [comment]
Alright, @maicki and @appleguy, updated to include a deprecated notice, and call the delegate first.

**Comment by maicki** [comment]
Hey @tberman can you please rebase the master branch of your fork on top of the latest upstream master and rebase this PR branch on top. We will likely merge that pretty soon. Thanks!

**Comment by hannahmbanana** [comment]
@tberman: We'd love to merge this into master today. Would it be possible to rebase this? Thanks!

**Comment by maicki** [comment]
@tberman Thank you very much for all of the work you put into that, we really appreciate it!

I pulled in your changes into a new PR as there where some merge conflicts: #2065 therefore I also will close this PR.

**Pull request closed without merging**
