### PR TITLE
Add target to podfiles

### PR DESCRIPTION
**Pull request by MatheusGodinho**
Fix the issue #1531, when you try to pod install you give a error because are missing the target to install.

### CODE REVIEW

**Comment by HeEAaD** [comment]
Travis failed because of the two following issues:

# Issue 1
> [!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

Solution: Use proper quotes `'` or `"`, not `“` in the podfiles.

# Issue 2
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Sample` to `Pods/Target Support Files/Pods-Sample/Pods-Sample.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Sample/Pods-Sample.debug.xcconfig` in your build configuration.

Solution: Clean the configurations in every sample project which uses Cocoapods.
1. open project
2. set "Based on Configuration File" to `None` (see screenshot)
3. remove `Pods.debug.xcconfig` and `Pods.release.xcconfig` from the project (see screenshot)
4. run `pod install`
5. commit the newly generated `Sample.xcodeproj`
clean_configs

## Note:
You can check that all examples building successfully by running `./build.sh examples`.

**Comment by appleguy** [comment]
@MatheusGodinho   Thanks for the change! Will you be able to address the build failure? If you don't have time or are away from the computer for several days, let us know so that someone from the community can take this over in close this PR.

**Comment by maicki** [comment]
@HeEAaD Step 2 in your description need stop be done with a pod version 1.0pre or can this also be done with 0.39.0?

**Comment by HeEAaD** [comment]
@maicki I guess 0.39 should be enough.

**Comment by appleguy** [comment]
See #1576 , hopefully that supercedes this.  Please message us on Slack if not!

**Pull request closed without merging**
