### PR TITLE
Clean Up Many Files

### PR DESCRIPTION
**Pull request by Adlai-Holler**
I was prospecting some new ideas and encountered some surprising issues.

- Make `ASRangeController.h` and the ASLayoutController headers non-public. This is technically **breaking API** but we shouldn't treat it as such. These classes were never meant for public access.
- Move the `shouldShowRangeDebugOverlay` property over to `ASDisplayNode` from `ASRangeController`. Also technically **breaking API** but we shouldn't treat it as such. This method is called only specifically for debugging, and it's not worth leaving `ASRangeController` public just for this one property.
- Fix broken file ref to `AsyncDisplayKit+Debug.h/.m`
- Move internal range controller debugging methods out of public header `AsyncDisplayKit+Debug.h`
- Remove `ASLayoutRangeModeCount` which was being used as an "invalid" `ASLayoutRangeMode` _and_ as the number of valid range modes (4).
  - I get why this was done. It's nice how it "auto-updates" as we add range modes.
  - But it's confusing as hell and incorrect. It's not a range mode. It's an integer. There is no "Count" range mode.
  - I added a `ASLayoutRangeModeUnspecified = -1` to represent a range mode that is unknown.
- Make `ASLayoutRangeTypeCount` an actual integer, rather than an `ASLayoutRangeType`. Again, cute, I get it, great job.

### CODE REVIEW

**Comment by maicki** [comment]
@Adlai-Holler If you fiddle around with the project anyway can you move the `Base` folder from the root directory into AsyncDisplayKit please.

**Comment by Adlai-Holler** [comment]
@maicki Good call. I went ahead and made some more file shuffles:
- `/AsyncDisplayKit` -> `/Source`
- `/AsyncDisplayKitTests` -> `/Tests`
- `/AsyncDisplayKitTestHost` -> `/Test/TestHost`

**Comment by nguyenhuy** [comment]
Cool! Thanks for updating BUCK file as well!

**Comment by 3a4oT** [comment]
@Adlai-Holler  Hey! Have you pushed new 2.2 podspec to the trunk?

**Comment by nguyenhuy** [comment]
@3a4oT 2.2 has not been pushed to CocoaPods yet. You can still try it using this: `pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit.git', :branch => '2.2'`

**Comment by 3a4oT** [comment]
@nguyenhuy thanks. Do we know a release date?

**Comment by nguyenhuy** [comment]
@3a4oT It will be publish within 24 hours. Btw, you can get way faster answers if you reach us on our Slack channel: http://asyncdisplaykit.org/slack.html

**Pull request merged**
