### PR TITLE
Ensure subclasses of ASCollectionViewFlowLayoutInspector call super f…

### PR DESCRIPTION
**Pull request by garrettmoon**
…or didChange methods.

### CODE REVIEW

**Comment by garrettmoon** [comment]
@maicki this should work, right?

**Comment by Adlai-Holler** [comment]
I think the goal is to enforce it for non-flow inspectors – for any object that conforms to ASCollectionViewLayoutInspecting which is tough.

**Comment by maicki** [comment]
Agree with Adlai, I think it's not a full solution and has some downsides.

The methods `didChangeCollectionViewDelegate:` and `didChangeCollectionViewDataSource:` are optional in the protocol. If we would add them in this way they become necessary to overwrite. We could provide a default implemenetation in the superclass, but as said it would not solve the problem for layout inspector that are not inherit from these two classes.

I think we have to think about issue from a different angle and put some more thinking into the whole architecture around `UICollectionViewLayout` and layout inspectors.

**Comment by garrettmoon** [comment]
Yup, closing this for now.

**Pull request closed without merging**
