### PR TITLE
Fixed crash on multiple -[ASTableView reloadData]. Implemented test

### PR DESCRIPTION
**Pull request by victormayorov**
I have removed _queuedRangeUpdate, such as it brakes -[ASRangeController visibleNodeIndexPathsDidChangeWithScrollDirection:] handler. Other blocks can be scheduled between visibleNodeIndexPathsDidChangeWithScrollDirection and updateVisibleNodeIndexPaths and can remove nodes from ASDataController.
Also _rangeIsValid should be invalidated before handlers -[ASRangeControllerDelegate rangeController:did...:withAnimationOption:]

### CODE REVIEW

**Comment by appleguy** [comment]
Thank you for debugging this — getting into this part of the codebase to make improvements is very important, yet not something that most engineers using the framework are equipped to do.

I will try to understand the underlying bug more deeply to see if there is any way we could fix it without removing the update coalescing completely.  I remember when we added the coalescing, and for certain use cases it was extremely important for performance.  Of course, no performance optimization is worth losing correctness / stability, so if there is not a quick solution that keeps both then we will land this as-is and find a new optimization later.

**Comment by appleguy** [comment]
I just tried reverting the changes to ASRangeController, but running your test.  The test passed, at least in the simulator.  Were you able to confirm if the test failed before?  What is the reproduction case for this crash so I can understand its code flow better?  Perhaps it fails on a device?

**Comment by appleguy** [comment]
@victormayorov tagging you in case that is needed to send a notification.  I will make sure we get this fix merged this weekend if I can get a reproduction case soon.  Thanks again!

**Comment by victormayorov** [comment]
@appleguy Looks like the test is not stable. You can try to run in multiple times. I've got exception:
Test Case '-[ASTableViewTests testReloadData]' started.
/Users/temp/Projects/VMASDK/AsyncDisplayKitTests/ASTableViewTests.m:121: error: -[ASTableViewTests testReloadData] : failed: caught "NSRangeException", "*** -[NSArray objectsAtIndexes:]: index 22 in index set beyond bounds for empty array"
(
	0   CoreFoundation                      0x0000000107500a75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001058a3bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010744bca3 -[NSArray objectsAtIndexes:] + 979
	3   AsyncDisplayKitTests                0x0000000110e95980 __ASFindElementsInMultidimensionalArrayAtIndexPaths_block_invoke + 128
	4   AsyncDisplayKitTests                0x0000000110e94a3b _ZL52ASRecursivelyUpdateMultidimensionalArrayAtIndexPathsP14NSMutableArrayPK7NSArrayRmP11NSIndexPathmU13block_pointerFvS0_P10NSIndexSetmE + 1531
	5   AsyncDisplayKitTests                0x0000000110e9468a _ZL52ASRecursivelyUpdateMultidimensionalArrayAtIndexPathsP14NSMutableArrayPK7NSArrayRmP11NSIndexPathmU13block_pointerFvS0_P10NSIndexSetmE + 586
	6   AsyncDisplayKitTests                0x0000000110e955d3 ASFindElementsInMultidimensionalArrayAtIndexPaths + 675
	7   AsyncDisplayKitTests                0x0000000110e89440 -[ASDataController nodesAtIndexPaths:] + 496
	8   AsyncDisplayKitTests                0x0000000110e913b0 -[ASTableView rangeController:nodesAtIndexPaths:] + 96
	9   AsyncDisplayKitTests                0x0000000110f183be -[ASRangeController updateVisibleNodeIndexPaths] + 2494
	10  Foundation                          0x00000001054592e5 __NSFireDelayedPerform + 387
	11  CoreFoundation                      0x00000001074686c4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	12  CoreFoundation                      0x0000000107468285 __CFRunLoopDoTimer + 1045
	13  CoreFoundation                      0x000000010742b59d __CFRunLoopRun + 1901
	14  CoreFoundation                      0x000000010742abc6 CFRunLoopRunSpecific + 470
	15  Foundation                          0x000000010545d0d2 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 275
	16  Foundation                          0x000000010549d881 -[NSRunLoop(NSRunLoop) runUntilDate:] + 78
	17  AsyncDisplayKitTests                0x0000000110e4d593 -[ASTableViewTests testReloadData] + 387
	18  CoreFoundation                      0x00000001073f85ec __invoking___ + 140
	19  CoreFoundation                      0x00000001073f8442 -[NSInvocation invoke] + 290
	20  XCTest                              0x00000001110510f7 -[XCTestCase invokeTest] + 253
	21  XCTest                              0x00000001110512f8 -[XCTestCase performTest:] + 150
	22  XCTest                              0x000000011105abf5 -[XCTest run] + 260
	23  XCTest                              0x000000011104fffb -[XCTestSuite performTest:] + 379
	24  XCTest                              0x000000011105abf5 -[XCTest run] + 260
	25  XCTest                              0x000000011104fffb -[XCTestSuite performTest:] + 379
	26  XCTest                              0x000000011105abf5 -[XCTest run] + 260
	27  XCTest                              0x000000011104fffb -[XCTestSuite performTest:] + 379
	28  XCTest                              0x000000011105abf5 -[XCTest run] + 260
	29  XCTest                              0x000000011104d0bc __25-[XCTestDriver _runSuite]_block_invoke + 56
	30  XCTest                              0x0000000111057ead -[XCTestObservationCenter _observeTestExecutionForBlock:] + 162
	31  XCTest                              0x000000011104cff0 -[XCTestDriver _runSuite] + 269
	32  XCTest                              0x000000011104da1d -[XCTestDriver _checkForTestManager] + 234
	33  XCTest                              0x000000011105daf0 +[XCTestProbe runTests:] + 182
	34  Foundation                          0x00000001054592e5 __NSFireDelayedPerform + 387
	35  CoreFoundation                      0x00000001074686c4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	36  CoreFoundation                      0x0000000107468285 __CFRunLoopDoTimer + 1045
	37  CoreFoundation                      0x000000010742b59d __CFRunLoopRun + 1901
	38  CoreFoundation                      0x000000010742abc6 CFRunLoopRunSpecific + 470
	39  GraphicsServices                    0x00000001091f1a58 GSEventRunModal + 161
	40  UIKit                               0x0000000105ae1580 UIApplicationMain + 1282
	41  AsyncDisplayKitTestHost             0x0000000105387ef3 main + 115
	42  libdyld.dylib                       0x00000001081af145 start + 1
	43  ???                                 0x000000000000000a 0x0 + 10
)
Test Case '-[ASTableViewTests testReloadData]' failed (0.136 seconds).

**Comment by appleguy** [comment]
OK, awesome.  I was able to create a test case that reproduces this nearly 100% of the time (I haven't hit a case where it didn't, but it does take variable periods of time — no more than 1-2 seconds on a Mac).  I also took some of your test implementation, which is much appreciated, and integrated it into my new PR from tonight's work on ASDataController.

I pushed to try to fix the serialization completely, but was unable to finish.  This thing is fairly complicated, as you have observed.  Nonetheless I did break off a part of the diff that is my work-in-progress (so the PR https://github.com/facebook/AsyncDisplayKit/pull/496 includes only the cleaned up portions).

Thanks both @victoria-chain and @victormayorov!  I am so glad to be close to a fix on this issue, and probably wouldn't have gotten momentum on starting it without your help.

**Comment by appleguy** [comment]
I integrated part of this fix in https://github.com/facebook/AsyncDisplayKit/pull/496

However, my test case was able to break this fix.  At this stage I'm not confident that the coalescing has to be removed.  I am going to leave it out until the rest of the logic is properly serialized, but it is great to have that spot in the code identified for closer inspection.

**Pull request closed without merging**
