### PR TITLE
[ASLayoutElementStyle] implement -description with sizing info

### PR DESCRIPTION
**Pull request by hannahmbanana**
This replaces the mysteriously failing #2452.

### CODE REVIEW

**Comment by hannahmbanana** [comment]
I give up. :(

**Comment by maicki** [comment]
@hannahmbanana Don't worry we will get it in :) let me take it over

**Comment by hannahmbanana** [comment]
@maicki - sure, thanks! It's failing on the `examples/Swift` project.

**Comment by maicki** [comment]
@hannahmbanana Should be fixed. Can you please pull and test again. Thanks!

**Comment by hannahmbanana** [comment]
thanks @maicki!

**Comment by nguyenhuy** [comment]
Please fix conflicts. Besides not being sure why we need to get rid of `ASDISPLAYNODE_INLINE`, LGTM 👍

**Comment by maicki** [comment]
@nguyenhuy Rebased on master, added `ASDISPLAYNODE_INLINE` back again. Can you get it another look and approve. Thanks!

**Pull request merged**
